correct bump-version and make executable

diff --git a/bump-version b/bump-version
--- a/bump-version
+++ b/bump-version
@@ -9,10 +9,10 @@ if [ $# -ne 1 ]; then
 	exit 1
 fi
 
-if ! sed -i 's/^GITFLOW_VERSION=.*$/GITFLOW_VERSION='$1'/g' git-flow-version; then
-	echo "Could not replace GITFLOW_VERSION variable." >&2
+if ! sed -i '' 's/^GITDRIP_VERSION=.*$/GITDRIP_VERSION='$1'/g' git-drip-version; then
+	echo "Could not replace GITDRIP_VERSION variable." >&2
 	exit 2
 fi
 
-git add git-flow-version
-git commit -m "Bumped version number to $1" git-flow-version
+git add git-drip-version
+git commit -m "Bumped version number to $1" git-drip-version
